version: '3.1'
services:
  stats-server:
    build: ./stat
    image: stat_image:v1.1.23
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow

  ewm-service:
    build: ./ewm
    image: ewm_image:v1.1.23
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow
