DROP TABLE IF EXISTS hits;
DROP TABLE IF EXISTS apps;
create table if not exists apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    -- Будущее расширение
    CONSTRAINT pk_apps PRIMARY KEY (id),
    CONSTRAINT UQ_name UNIQUE (name)
);

create table if not exists hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uri     VARCHAR(30) NOT NULL,
    ip      VARCHAR(16) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    id_apps BIGINT,
    CONSTRAINT pk_hits PRIMARY KEY (id),
    CONSTRAINT fk_app FOREIGN KEY (id_apps) REFERENCES apps (id)
);