DROP TABLE IF EXISTS hits;
create table if not exists hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR(32) NOT NULL,
    uri       VARCHAR(128) NOT NULL,
    ip        VARCHAR(16) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);