DROP TABLE IF EXISTS hits;
DROP TABLE IF EXISTS app;
create table if not exists app
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    -- Будущее расширение
    CONSTRAINT pk_apps PRIMARY KEY (id),
    CONSTRAINT UQ_name UNIQUE (name)
);

create table if not exists hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uri     VARCHAR(30) NOT NULL,
    ip      VARCHAR(16) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    app_id BIGINT,
    CONSTRAINT pk_hits PRIMARY KEY (id),
    CONSTRAINT fk_app FOREIGN KEY (app_id) REFERENCES app (id)
);