DROP TABLE IF EXISTS hit;
create table if not exists hit
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     varchar(200),
    uri     varchar(100),
    ip      varchar(30),
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);